### PR TITLE
📚 Add book covers

### PR DESCRIPTION
**Pull request by andreffs18**
This MR adds an image to each book card and increases the number of cards per row to 4 (instead of 3). 
> The link is simply the hardcoded url for static images on the Springer website + the book electronic ISBN

It would look something like this:
image

Cheers

### CODE REVIEW

**Comment by hnarayanan** [comment]
1. I did this initially and realised that the book covers add no more information than the title and author that’s already on the card. 😊

2. Also no, I don’t approve introducing docker to a project so basic.

**Comment by andreffs18** [comment]
Alright, was worth the shot 👍 

You can close it if it's no longer applicable.

**Comment by andreffs18** [comment]
Also, those changes regarding the README were misplaced is the PR. It was moved to https://github.com/hnarayanan/springer-books/pull/4. Cheers

**Comment by hnarayanan** [comment]
I'll leave it open. If more people introduce the same idea (as an indicator it is what people want), I'll merge your work in for credit. :)

**Comment by hnarayanan** [comment]
Thank you (again, and sorry). I have formally closed this project since the books are no longer available.

**Pull request closed without merging**
